"""Cada operação da especificação contra o servidor falso. Gerado por tools/sdkgen a partir de sdks/openapi/v1.json — não edite; rode python tools/sdkgen/sdkgen.py generate."""

from __future__ import annotations

import json
import unittest

from assinavelox import ApiResult, AssinaVelox, DownloadedFile, FileUpload, Page, models

from tests._support import UUID_V4, fake_url, fetch_trace, new_trace


class GeneratedOperationsTest(unittest.TestCase):
    def setUp(self) -> None:
        self.client = AssinaVelox(base_url=fake_url(), token="tok_teste_sdk")

    def check_trace(self, trace: str, operation: str, idempotency: str | None) -> None:
        records = fetch_trace(trace)
        self.assertTrue(records, "o servidor falso não recebeu o pedido")
        self.assertEqual(records[0]["operation"], operation)
        self.assertEqual(records[0]["violations"], [])
        key = records[0]["headers"].get("idempotency-key")
        if idempotency == "required":
            self.assertRegex(key or "", UUID_V4)
        elif idempotency == "optional":
            self.assertIsNone(key)

    def test_list_envelopes(self) -> None:
        headers, trace = new_trace()
        result = self.client.list_envelopes(headers=headers)
        self.assertIsInstance(result, Page)
        self.assertEqual(len(result.data), 2)
        self.assertEqual(result.next_cursor, "fake-cursor-2")
        self.assertIsInstance(result.data[0], models.Envelope)
        self.assertIsNotNone(result.data[0].created_at)
        self.assertIsNotNone(result.data[0].display_code)
        self.assertIsNotNone(result.data[0].id)
        self.assertIsNotNone(result.data[0].object)
        self.assertIsNotNone(result.data[0].recipients_count)
        self.assertIsNotNone(result.data[0].signed_count)
        self.assertIsNotNone(result.data[0].signing_order)
        self.assertIsNotNone(result.data[0].status)
        self.assertIsNotNone(result.data[0].status_label)
        self.assertIsNotNone(result.data[0].title)
        self.assertIsNotNone(result.data[0].updated_at)
        self.assertIsNotNone(result.data[0].viewers_count)
        self.assertTrue(result.data[0].raw)
        following = result.next_page()
        assert following is not None
        self.assertEqual(len(following.data), 1)
        self.assertFalse(following.has_more)
        self.assertIsNone(following.next_page())
        self.assertEqual(len(list(result.auto_paging_iter())), 3)
        self.check_trace(trace, "v1.envelopes.index", None)

    def test_create_envelope(self) -> None:
        headers, trace = new_trace()
        result = self.client.create_envelope(json.loads("{\"title\": \"exemplo de title\"}"), headers=headers)
        self.assertIsInstance(result, models.Envelope)
        self.assertIsNotNone(result.created_at)
        self.assertIsNotNone(result.display_code)
        self.assertIsNotNone(result.id)
        self.assertIsNotNone(result.object)
        self.assertIsNotNone(result.recipients_count)
        self.assertIsNotNone(result.signed_count)
        self.assertIsNotNone(result.signing_order)
        self.assertIsNotNone(result.status)
        self.assertIsNotNone(result.status_label)
        self.assertIsNotNone(result.title)
        self.assertIsNotNone(result.updated_at)
        self.assertIsNotNone(result.viewers_count)
        self.assertTrue(result.raw)
        self.check_trace(trace, "v1.envelopes.store", "required")

    def test_get_envelope(self) -> None:
        headers, trace = new_trace()
        result = self.client.get_envelope("01J00000000000000000000000", headers=headers)
        self.assertIsInstance(result, models.Envelope)
        self.assertIsNotNone(result.created_at)
        self.assertIsNotNone(result.display_code)
        self.assertIsNotNone(result.id)
        self.assertIsNotNone(result.object)
        self.assertIsNotNone(result.recipients_count)
        self.assertIsNotNone(result.signed_count)
        self.assertIsNotNone(result.signing_order)
        self.assertIsNotNone(result.status)
        self.assertIsNotNone(result.status_label)
        self.assertIsNotNone(result.title)
        self.assertIsNotNone(result.updated_at)
        self.assertIsNotNone(result.viewers_count)
        self.assertTrue(result.raw)
        self.check_trace(trace, "v1.envelopes.show", None)

    def test_upload_document(self) -> None:
        headers, trace = new_trace()
        result = self.client.upload_document("01J00000000000000000000000", FileUpload(content=b'%PDF-1.4\r\n% teste do SDK\x00\xff\r\n%%EOF\n', filename="contrato.pdf", content_type="application/pdf"), headers=headers)
        self.assertIsInstance(result, models.Document)
        self.assertIsNotNone(result.created_at)
        self.assertIsNotNone(result.id)
        self.assertIsNotNone(result.name)
        self.assertIsNotNone(result.object)
        self.assertIsNotNone(result.original_filename)
        self.assertIsNotNone(result.position)
        self.assertIsNotNone(result.processing_label)
        self.assertIsNotNone(result.processing_status)
        self.assertIsNotNone(result.ready)
        self.assertIsNotNone(result.source_type)
        self.assertTrue(result.raw)
        self.check_trace(trace, "v1.envelopes.documents.store", "required")

    def test_list_recipients(self) -> None:
        headers, trace = new_trace()
        result = self.client.list_recipients("01J00000000000000000000000", headers=headers)
        self.assertIsInstance(result, list)
        self.assertGreaterEqual(len(result), 1)
        self.assertIsInstance(result[0], models.Recipient)
        self.assertIsNotNone(result[0].id)
        self.assertIsNotNone(result[0].notifications_count)
        self.assertIsNotNone(result[0].object)
        self.assertIsNotNone(result[0].order)
        self.assertIsNotNone(result[0].role)
        self.assertIsNotNone(result[0].role_label)
        self.assertIsNotNone(result[0].status)
        self.assertIsNotNone(result[0].status_label)
        self.assertTrue(result[0].raw)
        self.check_trace(trace, "v1.envelopes.recipients.index", None)

    def test_sync_recipients(self) -> None:
        headers, trace = new_trace()
        result = self.client.sync_recipients("01J00000000000000000000000", json.loads("{\"recipients\": [{\"email\": \"ana@example.com\", \"name\": \"exemplo de name\"}], \"signing_order\": \"sequential\"}"), headers=headers)
        self.assertIsInstance(result, list)
        self.assertGreaterEqual(len(result), 1)
        self.assertIsInstance(result[0], models.Recipient)
        self.assertIsNotNone(result[0].id)
        self.assertIsNotNone(result[0].notifications_count)
        self.assertIsNotNone(result[0].object)
        self.assertIsNotNone(result[0].order)
        self.assertIsNotNone(result[0].role)
        self.assertIsNotNone(result[0].role_label)
        self.assertIsNotNone(result[0].status)
        self.assertIsNotNone(result[0].status_label)
        self.assertTrue(result[0].raw)
        self.check_trace(trace, "v1.envelopes.recipients.sync", "optional")

    def test_list_fields(self) -> None:
        headers, trace = new_trace()
        result = self.client.list_fields("01J00000000000000000000000", headers=headers)
        self.assertIsInstance(result, list)
        self.assertGreaterEqual(len(result), 1)
        self.assertIsInstance(result[0], models.Field)
        self.assertIsNotNone(result[0].auto)
        self.assertIsNotNone(result[0].h)
        self.assertIsNotNone(result[0].id)
        self.assertIsNotNone(result[0].object)
        self.assertIsNotNone(result[0].page)
        self.assertIsNotNone(result[0].required)
        self.assertIsNotNone(result[0].type)
        self.assertIsNotNone(result[0].w)
        self.assertIsNotNone(result[0].x)
        self.assertIsNotNone(result[0].y)
        self.assertTrue(result[0].raw)
        self.check_trace(trace, "v1.envelopes.fields.index", None)

    def test_sync_fields(self) -> None:
        headers, trace = new_trace()
        result = self.client.sync_fields("01J00000000000000000000000", json.loads("{\"fields\": [{\"h\": 0.5, \"page\": 1, \"type\": \"signature\", \"w\": 0.5, \"x\": 0.5, \"y\": 0.5}]}"), headers=headers)
        self.assertIsInstance(result, list)
        self.assertGreaterEqual(len(result), 1)
        self.assertIsInstance(result[0], models.Field)
        self.assertIsNotNone(result[0].auto)
        self.assertIsNotNone(result[0].h)
        self.assertIsNotNone(result[0].id)
        self.assertIsNotNone(result[0].object)
        self.assertIsNotNone(result[0].page)
        self.assertIsNotNone(result[0].required)
        self.assertIsNotNone(result[0].type)
        self.assertIsNotNone(result[0].w)
        self.assertIsNotNone(result[0].x)
        self.assertIsNotNone(result[0].y)
        self.assertTrue(result[0].raw)
        self.check_trace(trace, "v1.envelopes.fields.sync", "optional")

    def test_send_envelope(self) -> None:
        headers, trace = new_trace()
        result = self.client.send_envelope("01J00000000000000000000000", headers=headers)
        self.assertIsInstance(result, ApiResult)
        self.assertIsInstance(result.meta, dict)
        self.assertIsInstance(result.data, models.Envelope)
        self.assertIsNotNone(result.data.created_at)
        self.assertIsNotNone(result.data.display_code)
        self.assertIsNotNone(result.data.id)
        self.assertIsNotNone(result.data.object)
        self.assertIsNotNone(result.data.recipients_count)
        self.assertIsNotNone(result.data.signed_count)
        self.assertIsNotNone(result.data.signing_order)
        self.assertIsNotNone(result.data.status)
        self.assertIsNotNone(result.data.status_label)
        self.assertIsNotNone(result.data.title)
        self.assertIsNotNone(result.data.updated_at)
        self.assertIsNotNone(result.data.viewers_count)
        self.assertTrue(result.data.raw)
        self.check_trace(trace, "v1.envelopes.send", "required")

    def test_cancel_envelope(self) -> None:
        headers, trace = new_trace()
        result = self.client.cancel_envelope("01J00000000000000000000000", json.loads("{}"), headers=headers)
        self.assertIsInstance(result, ApiResult)
        self.assertIsInstance(result.meta, dict)
        self.assertIsInstance(result.data, models.Envelope)
        self.assertIsNotNone(result.data.created_at)
        self.assertIsNotNone(result.data.display_code)
        self.assertIsNotNone(result.data.id)
        self.assertIsNotNone(result.data.object)
        self.assertIsNotNone(result.data.recipients_count)
        self.assertIsNotNone(result.data.signed_count)
        self.assertIsNotNone(result.data.signing_order)
        self.assertIsNotNone(result.data.status)
        self.assertIsNotNone(result.data.status_label)
        self.assertIsNotNone(result.data.title)
        self.assertIsNotNone(result.data.updated_at)
        self.assertIsNotNone(result.data.viewers_count)
        self.assertTrue(result.data.raw)
        self.check_trace(trace, "v1.envelopes.cancel", "optional")

    def test_download_file(self) -> None:
        headers, trace = new_trace()
        result = self.client.download_file("01J00000000000000000000000", "original", headers=headers)
        self.assertIsInstance(result, DownloadedFile)
        self.assertTrue(result.content.startswith(b"%PDF"))
        self.assertEqual(result.content_type, "application/pdf")
        self.assertEqual(result.filename, "AV-000123-original.pdf")
        self.check_trace(trace, "v1.envelopes.files.show", None)

    def test_list_events(self) -> None:
        headers, trace = new_trace()
        result = self.client.list_events("01J00000000000000000000000", headers=headers)
        self.assertIsInstance(result, Page)
        self.assertEqual(len(result.data), 2)
        self.assertEqual(result.next_cursor, "fake-cursor-2")
        self.assertIsInstance(result.data[0], models.Event)
        self.assertIsNotNone(result.data[0].id)
        self.assertIsNotNone(result.data[0].kind)
        self.assertIsNotNone(result.data[0].label)
        self.assertIsNotNone(result.data[0].object)
        self.assertIsNotNone(result.data[0].occurred_at)
        self.assertIsNotNone(result.data[0].type)
        self.assertTrue(result.data[0].raw)
        following = result.next_page()
        assert following is not None
        self.assertEqual(len(following.data), 1)
        self.assertFalse(following.has_more)
        self.assertIsNone(following.next_page())
        self.assertEqual(len(list(result.auto_paging_iter())), 3)
        self.check_trace(trace, "v1.envelopes.events.index", None)

    def test_get_verification(self) -> None:
        headers, trace = new_trace()
        result = self.client.get_verification("01J00000000000000000000000", headers=headers)
        self.assertIsInstance(result, dict)
        self.check_trace(trace, "v1.envelopes.verification.show", None)

    def test_list_templates(self) -> None:
        headers, trace = new_trace()
        result = self.client.list_templates(headers=headers)
        self.assertIsInstance(result, Page)
        self.assertEqual(len(result.data), 2)
        self.assertEqual(result.next_cursor, "fake-cursor-2")
        self.assertIsInstance(result.data[0], models.Template)
        self.assertIsNotNone(result.data[0].id)
        self.assertIsNotNone(result.data[0].name)
        self.assertIsNotNone(result.data[0].object)
        self.assertIsNotNone(result.data[0].source_type)
        self.assertIsNotNone(result.data[0].status)
        self.assertIsNotNone(result.data[0].updated_at)
        self.assertIsNotNone(result.data[0].usable)
        self.assertTrue(result.data[0].raw)
        following = result.next_page()
        assert following is not None
        self.assertEqual(len(following.data), 1)
        self.assertFalse(following.has_more)
        self.assertIsNone(following.next_page())
        self.assertEqual(len(list(result.auto_paging_iter())), 3)
        self.check_trace(trace, "v1.templates.index", None)

    def test_get_template(self) -> None:
        headers, trace = new_trace()
        result = self.client.get_template("01J00000000000000000000000", headers=headers)
        self.assertIsInstance(result, models.Template)
        self.assertIsNotNone(result.id)
        self.assertIsNotNone(result.name)
        self.assertIsNotNone(result.object)
        self.assertIsNotNone(result.source_type)
        self.assertIsNotNone(result.status)
        self.assertIsNotNone(result.updated_at)
        self.assertIsNotNone(result.usable)
        self.assertTrue(result.raw)
        self.check_trace(trace, "v1.templates.show", None)

    def test_create_envelope_from_template(self) -> None:
        headers, trace = new_trace()
        result = self.client.create_envelope_from_template("01J00000000000000000000000", json.loads("{}"), headers=headers)
        self.assertIsInstance(result, models.Envelope)
        self.assertIsNotNone(result.created_at)
        self.assertIsNotNone(result.display_code)
        self.assertIsNotNone(result.id)
        self.assertIsNotNone(result.object)
        self.assertIsNotNone(result.recipients_count)
        self.assertIsNotNone(result.signed_count)
        self.assertIsNotNone(result.signing_order)
        self.assertIsNotNone(result.status)
        self.assertIsNotNone(result.status_label)
        self.assertIsNotNone(result.title)
        self.assertIsNotNone(result.updated_at)
        self.assertIsNotNone(result.viewers_count)
        self.assertTrue(result.raw)
        self.check_trace(trace, "v1.templates.envelopes.store", "required")

    def test_list_webhook_events(self) -> None:
        headers, trace = new_trace()
        result = self.client.list_webhook_events(headers=headers)
        self.assertIsInstance(result, list)
        self.assertGreaterEqual(len(result), 1)
        self.check_trace(trace, "v1.webhook_events.index", None)

    def test_get_webhook_event_sample(self) -> None:
        headers, trace = new_trace()
        result = self.client.get_webhook_event_sample("envelope.sent", headers=headers)
        self.assertIsInstance(result, ApiResult)
        self.assertIsInstance(result.meta, dict)
        self.assertIsInstance(result.data, list)
        self.assertGreaterEqual(len(result.data), 1)
        self.check_trace(trace, "v1.webhook_events.sample", None)

    def test_list_webhook_subscriptions(self) -> None:
        headers, trace = new_trace()
        result = self.client.list_webhook_subscriptions(headers=headers)
        self.assertIsInstance(result, ApiResult)
        self.assertIsInstance(result.meta, dict)
        self.assertIsInstance(result.data, list)
        self.assertGreaterEqual(len(result.data), 1)
        self.assertIsInstance(result.data[0], models.WebhookSubscription)
        self.assertIsNotNone(result.data[0].id)
        self.assertIsNotNone(result.data[0].object)
        self.assertIsNotNone(result.data[0].target_url)
        self.assertIsNotNone(result.data[0].status)
        self.assertIsNotNone(result.data[0].status_label)
        self.assertIsNotNone(result.data[0].secret_hint)
        self.assertIsNotNone(result.data[0].signature_header)
        self.assertIsNotNone(result.data[0].created_at)
        self.assertTrue(result.data[0].raw)
        self.check_trace(trace, "v1.webhook_subscriptions.index", None)

    def test_create_webhook_subscription(self) -> None:
        headers, trace = new_trace()
        result = self.client.create_webhook_subscription(json.loads("{\"target_url\": \"https://integracao.example/webhooks/assinavelox\"}"), headers=headers)
        self.assertIsInstance(result, ApiResult)
        self.assertIsInstance(result.meta, dict)
        self.assertIsInstance(result.data, models.WebhookSubscription)
        self.assertIsNotNone(result.data.id)
        self.assertIsNotNone(result.data.object)
        self.assertIsNotNone(result.data.target_url)
        self.assertIsNotNone(result.data.status)
        self.assertIsNotNone(result.data.status_label)
        self.assertIsNotNone(result.data.secret_hint)
        self.assertIsNotNone(result.data.signature_header)
        self.assertIsNotNone(result.data.created_at)
        self.assertTrue(result.data.raw)
        self.check_trace(trace, "v1.webhook_subscriptions.store", "required")

    def test_delete_webhook_subscription(self) -> None:
        headers, trace = new_trace()
        result = self.client.delete_webhook_subscription("01J00000000000000000000000", headers=headers)
        self.assertIsNone(result)
        self.check_trace(trace, "v1.webhook_subscriptions.destroy", None)

    def test_create_embedded_session(self) -> None:
        headers, trace = new_trace()
        result = self.client.create_embedded_session("01J00000000000000000000000", "01J00000000000000000000000", json.loads("{\"origin\": \"exemplo de origin\"}"), headers=headers)
        self.assertIsInstance(result, models.EmbeddedSigningSession)
        self.assertIsNotNone(result.id)
        self.assertIsNotNone(result.object)
        self.assertIsNotNone(result.origin)
        self.assertIsNotNone(result.status)
        self.assertTrue(result.raw)
        self.check_trace(trace, "v1.envelopes.recipients.embedded_sessions.store", "required")

    def test_get_embedded_session(self) -> None:
        headers, trace = new_trace()
        result = self.client.get_embedded_session("01J00000000000000000000000", "01J00000000000000000000000", "01J00000000000000000000000", headers=headers)
        self.assertIsInstance(result, models.EmbeddedSigningSession)
        self.assertIsNotNone(result.id)
        self.assertIsNotNone(result.object)
        self.assertIsNotNone(result.origin)
        self.assertIsNotNone(result.status)
        self.assertTrue(result.raw)
        self.check_trace(trace, "v1.envelopes.recipients.embedded_sessions.show", None)

    def test_revoke_embedded_session(self) -> None:
        headers, trace = new_trace()
        result = self.client.revoke_embedded_session("01J00000000000000000000000", "01J00000000000000000000000", "01J00000000000000000000000", headers=headers)
        self.assertIsInstance(result, models.EmbeddedSigningSession)
        self.assertIsNotNone(result.id)
        self.assertIsNotNone(result.object)
        self.assertIsNotNone(result.origin)
        self.assertIsNotNone(result.status)
        self.assertTrue(result.raw)
        self.check_trace(trace, "v1.envelopes.recipients.embedded_sessions.destroy", None)


if __name__ == "__main__":
    unittest.main()
